const operators = [
  {
    name: "Ace",
    gender: "Male",
    side: "Attacker",
    price: 19.99,
    image: "/public/ace.jpg",
  },
  {
    name: "Alibi",
    gender: "Female",
    side: "Defender",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Amaru",
    gender: "Female",
    side: "Attacker",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Aruni",
    gender: "Female",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Ash",
    gender: "Female",
    side: "Attacker",
    price: 19.99,
    image: "./public/",
  },
  {
    name: "Azami",
    gender: "Female",
    side: "Defender",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Bandit",
    gender: "Male",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Blitz",
    gender: "Male",
    side: "Attacker",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Brava",
    gender: "Female",
    side: "Attacker",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Buck",
    gender: "Male",
    side: "Attacker",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Castle",
    gender: "Male",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Caveira",
    gender: "Female",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Clash",
    gender: "Female",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Deimos",
    gender: "Male",
    side: "Attacker",
    price: 19.99,
    image: "./public/",
  },
  {
    name: "Doc",
    gender: "Male",
    side: "Defender",
    price: 14.99,
    image: "./public/",
  },
  {
    name: "Dokkaebi",
    gender: "Female",
    side: "Attacker",
    price: 19.99,
    image: "./public/",
  },
  {
    name: "Echo",
    gender: "Male",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Ela",
    gender: "Female",
    side: "Defender",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Fuze",
    gender: "Male",
    side: "Attacker",
    price: 9.99,
    image: "./public/",
  },
  {
    name: "Glaz",
    gender: "Male",
    side: "Attacker",
    price: 9.99,
    image: "./public/",
  },
];
export { operators };
