const operators = [
  { name: "Ace", gender: "Male", side: "Attacker", price: 29.99, image: "" },
  {
    name: "Alibi",
    gender: "Female",
    side: "Defender",
    price: 39.99,
    image: "",
  },
  { name: "Amaru", gender: "Female", side: "Attacker", price: 9.99, image: "" },
  {
    name: "Aruni",
    gender: "Female",
    side: "Defender",
    price: 24.99,
    image: "",
  },
  { name: "Ash", gender: "Female", side: "Attacker", price: 49.99, image: "" },
  {
    name: "Azami",
    gender: "Female",
    side: "Defender",
    price: 59.99,
    image: "",
  },
  { name: "Bandit", gender: "Male", side: "Defender", price: 34.99, image: "" },
  { name: "Blitz", gender: "Male", side: "Attacker", price: 74.99, image: "" },
  {
    name: "Brava",
    gender: "Female",
    side: "Attacker",
    price: 19.99,
    image: "",
  },
  { name: "Buck", gender: "Male", side: "Attacker", price: 14.99, image: "" },
  { name: "Castle", gender: "Male", side: "Defender", price: 39.99, image: "" },
  {
    name: "Caveira",
    gender: "Female",
    side: "Defender",
    price: 44.99,
    image: "",
  },
  {
    name: "Clash",
    gender: "Female",
    side: "Defender",
    price: 54.99,
    image: "",
  },
  { name: "Deimos", gender: "Male", side: "Attacker", price: 19.99, image: "" },
  { name: "Doc", gender: "Male", side: "Defender", price: 29.99, image: "" },
  {
    name: "Dokkaebi",
    gender: "Female",
    side: "Attacker",
    price: 39.99,
    image: "",
  },
  { name: "Echo", gender: "Male", side: "Defender", price: 29.99, image: "" },
  { name: "Ela", gender: "Female", side: "Defender", price: 15.99, image: "" },
  { name: "Fuze", gender: "Male", side: "Attacker", price: 69.99, image: "" },
  { name: "Glaz", gender: "Male", side: "Attacker", price: 49.99, image: "" },
];
export { operators };
